### ISSUE TITLE
Bad apiversion in #132

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/moc-apps#134]
In #132, we create the `curator-auth-proxy` clusterrole as:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
```

But that's the wrong `apiVersion`, and results in the error:

```
no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
```

The correct `apiVersion` is `rbac.authorization.k8s.io/v1`

**Comment by larsks** [comment]
@skanthed I'm submitting a fix for this, but the above error means that the changes from #132 haven't been successfully applied to the cluster yet.

**Comment by skanthed** [comment]
Got you. Thank you so much.
