### ISSUE TITLE
Deploy Coldfront with OpenShift support for the MOC

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/moc-apps#166]
We're currently using Coldfront on the NERC to manage OpenStack users. We want to adapt the same workflow for the MOC, but with managing OpenShift instead of OpenStack.

This task refers to managing the MOC managed OpenShift and is unrelate to the NERC OpenShift effort. If we are going to deprecate the MOC maintained OpenShift in favor of NERC, this task should be closed.

- [ ] Adapt `coldfront-nerc` manifests and image for MOC deployment.
- [ ] Deploy via Argo CD
- [ ] Test, document and demo

**Comment by joachimweyl** [comment]
This will be done on the NERC but not MOC.
